### ISSUE TITLE
rest API to support metadata-recorder

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/metadata-catalog#73]
[x] PUT  with body as metadata of [trackingId, filename, dataset, fileSize, geometry, fileMetadata]
[ ] Response needs to mimic that of legacy catalog-metadata (empty map response if status 200 or 201, response with 'message' otherwise)
(Decided this is part of extraction [ ] Type needs to be dynamically generated based on dataset and file extension (MetadataTypeUtility behavior from legacy catalog-metadata))
[ ] Check that response from storage for a POST contains what was sent to be saved (so no silent failure)
[ ] Change trackingId to id, requires changing storage module to use java UUID not datastax UUID.

**Comment by erinreeves** [comment]
Needs to have it's response updated to what's in the legacy catalog-metadata controller, not service, since controller changes the response a lot.
