### ISSUE TITLE
migrate cu nginx config to the admin project, then add proxy for metadata-catalog

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/metadata-catalog#91]
[adimin project](https://github.com/cires-ncei/cu-server-admin)

**Comment by ChrisEsterlein** [comment]
You can see the new global nginx config in the 'nginx' role.
You can find the metadata-catalog proxy config in the 'metadata-catalog' role. 
https://github.com/cedardevs/cu-server-admin/tree/master/roles
