### ISSUE TITLE
change storage module to init the database as needed

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/metadata-catalog#97]
Delete the custom cassandra init image and docker hub repo.

Make this a feature toggle. Default should be not to init, and the docker-compose.yml for integration tests and the deployment should change that value to init.

**Comment by mcquinne** [comment]
### Note:

Once we do this, we should able to clean up some of the gradle/docker tricks that we're using to support integration tests and deployment. Specifically:

- In storage:
    - Remove `cassandraDockerImage` gradle task
    - Remove `publishCassandraImage` gradle task
    - Remove `metadata-catalog-cassandra-init` tagging/pushing from the `promote` task
    - Delete `src/resources/docker/template_cassandraDockerfile`
    - Delete `src/resources/docker/scripts/template_initialize_cassandra.sh`
- In project root:
    - Remove the `wait` service from `docker-compose.yml`
